### PR TITLE
Add --exclude and --interactive options

### PR DESCRIPTION
**Pull request by ddelange**
Taken from bitdivision:master (nice one @bitdivision)

@thomasjahoda could you add a development section to the readme? For instance which command to run to [bump the version](https://github.com/peritus/bumpversion#usage)? Or would you take care of that after this PR is merged? Anything else I can add to the PR? Had a look at the Makefile, ran pytest and flake8.

### CODE REVIEW

**Comment by thomasjahoda** [comment]
@ddelange Thanks for the contribution, I'll take a look at it in the coming week 👍

**Comment by ddelange** [comment]
@thomasjahoda any update on merging&releasing this? we would like to use `-p` flag from master which is also not yet on pypi

**Comment by ddelange** [comment]
@thomasjahoda if you need help maintaining pypi and this repo, let me know :)

**Comment by thomasjahoda** [comment]
@ddelange Thanks for the help, I invited you as collaborator for this repo 😅
Sorry for never answering, a lot of stuff that is more important to me is going on right now. I wanted to review the pull requests but I guess I'll just leave the whole job to you if you'd be so nice.
(I also added you as maintainer on the pypi project.)

**Comment by ddelange** [comment]
@thomasjahoda all good! no worries. I'll hold the fort :)

**Pull request merged**
